### ISSUE TITLE
Add hyperlink into the cell definition.

### ISSUE THREAD

**Issue by acautin** [K2InformaticsGmbH/erlxlsx#3]
Instead of having a separated map to define the hyperlinks for the cells, it would look nicer if we could define them directly together with the data.

Something like:

``3 => #{'A' => #{style => 2, data => "K2 Home", hyperlink => "http://www.k2informatics.ch"}}``

**Comment by c-bik** [comment]
lets call it `link` / `href` instead of `hyperlink`?

**Comment by c-bik** [comment]
Fixed with https://github.com/K2InformaticsGmbH/erlxlsx/commit/af8a071ed1fdc058b343331e61e0d98f1e2ba295
